# Force S2I strategy (Binary build)
quarkus.openshift.build-strategy=s2i

# Ensure the app is actually deployed after building
quarkus.kubernetes.deploy=true
quarkus.openshift.route.expose=true

# The URL of your Python FastAPI Service (Internal OpenShift Service Name)
quarkus.rest-client.detection-api.url=http://python-ai-service:8080

# Increase max body size for high-res X-ray images
quarkus.http.limits.max-body-size=20M
